# Word Embedding

### On this file i just try to embedded the simple words for understanding.

## Importing the libraries and dependencies

In [19]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [20]:
# short review description
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [21]:
one_hot("amazing restaurant",30)

[19, 21]

In [22]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[9, 25], [19, 21], [6, 26], [27, 28, 26], [1, 7, 20], [8, 25], [21, 7, 22], [23, 2], [23, 8], [9, 8]]


In [33]:
max_length = 3
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[ 9 25  0]
 [19 21  0]
 [ 6 26  0]
 [27 28 26]
 [ 1  7 20]
 [ 8 25  0]
 [21  7 22]
 [23  2  0]
 [23  8  0]
 [ 9  8  0]]


In [38]:
embeded_vector_size = 4

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [39]:
X = padded_reviews
y = sentiment

In [45]:
model.build(input_shape=(None, max_length))
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 3, 4)           │           120 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_4 (Flatten)             │ (None, 12)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 1)              │            13 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 133 (532.00 B)

 Trainable params: 133 (532.00 B)

 Non-trainable params: 0 (0.00 B)

In [50]:
model.fit(X, y, epochs=50)



Epoch 1/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 1.0000 - loss: 0.5490
Epoch 2/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 1.0000 - loss: 0.5472
Epoch 3/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 1.0000 - loss: 0.5455
Epoch 4/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step - accuracy: 1.0000 - loss: 0.5438
Epoch 5/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 1.0000 - loss: 0.5420
Epoch 6/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 1.0000 - loss: 0.5403
Epoch 7/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 1.0000 - loss: 0.5385
Epoch 8/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 1.0000 - loss: 0.5368
Epoch 9/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 1.0000 - loss: 0.5350
Epoch 10/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 1.0000 - loss: 0.5332
Epoch 11/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 1.0000 - loss: 0.5315
Epoch 12/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 1.0000 - loss: 0.5297


In [48]:
# evaluate the model
loss, accuracy = model.evaluate(X, y)
accuracy



1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 167ms/step - accuracy: 0.9000 - loss: 0.6283


0.8999999761581421

In [51]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [52]:
weights[13]



array([-0.04208021, -0.04170942, -0.02697917,  0.02063349], dtype=float32)

In [53]:
weights[4]

array([ 0.01938142, -0.01744844,  0.01184471, -0.02781179], dtype=float32)

In [57]:
weights[25]

array([ 0.03144205, -0.03132678,  0.03536377,  0.03084308], dtype=float32)

In [58]:
weights[28]

array([-0.1615125 ,  0.13083273, -0.14816551,  0.16632736], dtype=float32)

This notebook demonstrates Word Embeddings using TensorFlow/Keras.

Key steps performed:<br>
    Data Prep: Created a small dataset of 10 restaurant reviews with binary sentiment labels.<br>
    Encoding: Converted text to integers using one_hot encoding (vocab size 30) and pad_sequences to ensure a uniform input length of 3.<br>
    Modeling: Built a Sequential model with an Embedding layer (4-dimensional vectors), a Flatten layer, and a Dense output.<br>
    Training: Trained the model to associate specific words with positive/negative sentiments.<br>
    Inspection: Extracted and examined the learned weight vectors (embeddings) for specific words to see how the model represents them numerically.

